spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    database: MYSQL
    database-platform: H2
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  ## for dev only
  h2:
    console:
      enabled: true

logging:
  level:
    com.tumblbug: debug


